#!/bin/sh

sed -i 's/-DKDE4_BUILD_TESTS=false/-DKDE4_BUILD_TESTS=true/' debian/rules
debian/rules clean 2>&1
dpkg-source --before-build .
debian/rules binary 2>&1
xvfb-run -a --server-args="-screen 0 1024x768x24" \
    dbus-launch --exit-with-session debian/tests/testsuite.xsession
