#!/bin/sh

allowed_packages="kde4libs kdepimlibs kdebase-runtime ktorrent"

set -e
test -x /usr/bin/dpkg-parsechangelog || exit 0

dir=`pwd`
while [ -n "$dir" ] && [ "$dir" != '/' ]; do
    if [ -e debian/changelog ]; then
        source=`/usr/bin/dpkg-parsechangelog | grep '^Source:' | sed 's/^Source:[[:space:]]*\([^[:space:]]\+\).*/\1/'`
        distro=`/usr/bin/dpkg-parsechangelog | grep '^Distribution:' | sed 's/^Distribution:[[:space:]]*\([^[:space:]]\+\).*/\1/'`
        if [ "$distro" = "unstable" ] && ! echo $allowed_packages | grep -q "\b$source\b"; then
            echo "NOTE from Debian KDE maintainers: DO NOT upload KDE 4 based packages to Debian unstable yet" >&2
            exit 1
        fi
    fi
    dir=`dirname "$dir"`
    cd "$dir"
done

exit 0
