#!/bin/sh -e

# Removes non-free files from the source tree. Must be done before
# creating the orig.tar.gz.

TOPLEVEL="$1"

if [ "$TOPLEVEL" = "" ]; then
	echo "Please provide the toplevel directory as the argument."
	exit 1
else
	rm -f $TOPLEVEL/kioslave/http/kcookiejar/rfc2109
	rm -f $TOPLEVEL/kioslave/http/kcookiejar/rfc2965
	rm -f $TOPLEVEL/kio/kssl/KPMG-CA-16389.0.DC80502.pdf
fi

exit 0
